"use client"

import { Catalogue, Features, Intro } from '@/components'
import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cars Hub | Best Car Rental Platrofm in Indian',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <React.Fragment>
      <Intro />
      <Catalogue/>
      <Features />
    </React.Fragment>
  )
}
