import React from 'react';
import type { Metadata } from 'next'
import { CustomInput, CustomButton } from '@/components';
import { BsArrowRightShort, BsLink45Deg } from 'react-icons/bs';

export const metadata: Metadata = {
  title: 'Admin Login',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <React.Fragment>
      <main className="h-screen w-full bg-admin-complement grid lg:grid-cols-2 md:grid-cols-2 sm:grid-cols-1">
        <section className="h-full flex items-center justify-center">
          <div className="lg:w-6/12 md:w-8/12 sm:w-10/12">
            {children}
          </div>
        </section>
        <section className="relative lg:block md:block sm:hidden">
          <div className="bg-cover bg-center bg-no-repeat absolute h-screen w-full" style={{ backgroundImage: "url('/assets/login-bg.png')" }}>
            <div className="absolute h-full w-full flex items-center justify-center">
              <div className="lg:w-8/12 md:w-8/12 sm:w-10/12 text-center space-y-5">
                <div>
                  <img src="/assets/logo-white.png" alt="logo" className='h-[50px] w-auto mx-auto' />
                </div>
                <div className="flex items-center justify-center space-x-5">
                  <hr className="bg-white h-[2px] w-[70px] rounded-full" />
                  <p className="font-medium text-lg text-white">Administrator Panel</p>
                  <hr className="bg-white h-[2px] w-[70px] rounded-full" />
                </div>
                <p className="leading-loose text-xs text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Aperiam beatae eligendi quis, minima tempore molestias.</p>
                <div className='flex items-center justify-center'>
                  <CustomButton type='submit' text='Visit Website' theme='light' rightIcon={<BsLink45Deg size={20} className='ml-1' />} />
                </div>

              </div>
            </div>
          </div>
        </section>
      </main>
    </React.Fragment>
  )
}