import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cars Hub | Best Car Rental Platrofm in Indian',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>page</div>
  )
}

export default page