import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
}

const Dashboard = () => {
  return (
    <div>Dashboard</div>
  )
}

export default Dashboard