import React from 'react'
import type { Metadata } from 'next'
import { CustomInput, CustomButton } from '@/components';
import { BsArrowRightShort } from 'react-icons/bs';

export const metadata: Metadata = {
  title: 'Admin Login',
  description: 'Generated by create next app',
}

const Login = () => {
  return (
    <React.Fragment>
      <figure>
        <form className="space-y-6">

          <div className="space-y-3">
            <h1 className="font-semibold text-ascent text-4xl">Sign In</h1>
            <p className="text-xs text-gray-500">Enter your email and password to sign in!</p>
          </div>

          <CustomInput name='email' type='email' placeHolder='Email Address' value={''} label='Email Address' required={true} />
          <CustomInput name='password' type='password' placeHolder='Password' value={''} label='Password' required={true} />
          <CustomButton type='submit' text='Submit' styles='w-full' theme='primary' rightIcon={<BsArrowRightShort size={20} strokeWidth={0.5} className='ml-1' />} />

          <div>
            <p className="text-xs">Forgot your password ? <a href="#" className="link">Reset Password</a></p>
          </div>

        </form>
      </figure>
    </React.Fragment>
  )
}

export default Login
