import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cars Hub | Best Car Rental Platrofm in Indian',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <React.Fragment>
        <section>
            this is dashboard
        </section>
    </React.Fragment>
  )
}
